export const COURSE_LIST_REQUEST = 'COURSE_LIST_REQUEST'
export const COURSE_LIST_SUCCESS = 'COURSE_LIST_SUCCESS'
export const COURSE_LIST_FAIL = 'COURSE_LIST_FAIL'


export const COURSE_LATEST_REQUEST = 'COURSE_LATEST_REQUEST'
export const COURSE_LATEST_SUCCESS = 'COURSE_LATEST_SUCCESS'
export const COURSE_LATEST_FAIL = 'COURSE_LATEST_FAIL'