export const SOFTWARE_PREVIOUS_REQUEST = 'SOFTWARE_PREVIOUS_REQUEST'
export const SOFTWARE_PREVIOUS_SUCCESS = 'SOFTWARE_PREVIOUS_SUCCESS'
export const SOFTWARE_PREVIOUS_FAIL = 'SOFTWARE_PREVIOUS_FAIL'


export const SOFTWARE_DETAILS_REQUEST = 'SOFTWARE_DETAILS_REQUEST'
export const SOFTWARE_DETAILS_SUCCESS = 'SOFTWARE_DETAILS_SUCCESS'
export const SOFTWARE_DETAILS_FAIL = 'SOFTWARE_DETAILS_FAIL'