# Generated by Django 3.2 on 2021-05-04 01:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_auto_20210503_2336'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='weight',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
