# Generated by Django 3.2 on 2021-05-12 12:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('base', '0003_product_weight'),
    ]

    operations = [
        migrations.CreateModel(
            name='Software',
            fields=[
                ('name', models.CharField(blank=True, max_length=200, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
                ('version', models.IntegerField(blank=True, default=0, null=True)),
                ('mainFeature', models.CharField(blank=True, max_length=200, null=True)),
                ('licenseUse', models.CharField(blank=True, max_length=200, null=True)),
                ('downloadSize', models.IntegerField(blank=True, default=0, null=True)),
                ('downloadNumber', models.IntegerField(blank=True, default=0, null=True)),
                ('releasedAt', models.DateTimeField(auto_now_add=True)),
                ('feature1', models.CharField(blank=True, max_length=200, null=True)),
                ('image1', models.ImageField(blank=True, null=True, upload_to='')),
                ('description1', models.TextField(blank=True, null=True)),
                ('feature2', models.CharField(blank=True, max_length=200, null=True)),
                ('image2', models.ImageField(blank=True, null=True, upload_to='')),
                ('description2', models.TextField(blank=True, null=True)),
                ('feature3', models.CharField(blank=True, max_length=200, null=True)),
                ('image3', models.ImageField(blank=True, null=True, upload_to='')),
                ('description3', models.TextField(blank=True, null=True)),
                ('_id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
