# Generated by Django 3.2 on 2021-05-12 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_software'),
    ]

    operations = [
        migrations.AlterField(
            model_name='software',
            name='downloadSize',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='software',
            name='version',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
    ]
