# Generated by Django 3.2 on 2021-05-12 16:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_feature'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Feature',
        ),
    ]
