# Generated by Django 3.2 on 2021-05-13 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_delete_feature'),
    ]

    operations = [
        migrations.AddField(
            model_name='software',
            name='mainFeatureImage',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
