# Generated by Django 3.2 on 2021-05-13 21:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('base', '0008_software_mainfeatureimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='software',
            name='mainFeatureDescription',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('name', models.CharField(blank=True, max_length=200, null=True)),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='')),
                ('length', models.FloatField(blank=True, default=0, null=True)),
                ('sections', models.IntegerField(blank=True, default=0, null=True)),
                ('lectures', models.IntegerField(blank=True, default=0, null=True)),
                ('intro', models.TextField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('author', models.CharField(blank=True, max_length=200, null=True)),
                ('level', models.IntegerField(blank=True, default=0, null=True)),
                ('tools', models.DateTimeField(auto_now_add=True)),
                ('price', models.FloatField(blank=True, default=0, null=True)),
                ('projectFilesAvailable', models.BooleanField(default=False)),
                ('_id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
