# Generated by Django 3.2 on 2021-05-13 21:55

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_auto_20210513_2226'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='createdAt',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2021, 5, 13, 21, 55, 39, 14467, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='course',
            name='level',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='tools',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
