# Generated by Django 3.2 on 2021-05-17 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0010_auto_20210513_2255'),
    ]

    operations = [
        migrations.AddField(
            model_name='software',
            name='status',
            field=models.CharField(choices=[('LTS', 'Lts'), ('stable', 'Stable'), ('alpha', 'Alpha'), ('beta', 'Beta')], default='stable', max_length=50),
        ),
    ]
