# Generated by Django 3.2 on 2021-05-21 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0011_software_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='height',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='width',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
