# Generated by Django 3.2 on 2021-05-24 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0012_auto_20210521_2313'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='like',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
