# Generated by Django 3.2 on 2021-05-24 21:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0014_pfp'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Pfp',
        ),
    ]
