# Generated by Django 3.2 on 2021-06-04 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0016_course_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='versionUsed',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
